import type {
  WorkItem,
  Person,
  Team,
  ProjectConfig,
  PIConfig,
  GitStatus,
  ObjectivesData,
} from '../types/edpa';
import type { EdpaSnapshot } from '../types/snapshot';

// ─── Snapshot mode ───────────────────────────────────────────────────────────
// When the page is generated by `plugin/edpa/scripts/pi_planning.py`, the whole
// project state is injected as `window.__EDPA__` (the versioned EDPA snapshot
// contract — see types/snapshot.ts). In that mode the app is strictly
// READ-ONLY: every GET resolves from the snapshot, every write rejects. With no
// snapshot present (Vite dev or the Express server) we fall back to the live
// `/api` backend unchanged.

declare global {
  interface Window {
    __EDPA__?: EdpaSnapshot;
  }
}

const SNAP: EdpaSnapshot | undefined =
  typeof window !== 'undefined' ? window.__EDPA__ : undefined;

/** True when running from a generated self-contained snapshot (read-only). */
export const isSnapshot = SNAP !== undefined;

const readonly = (): Promise<never> =>
  Promise.reject(
    new Error('EDPA snapshot is read-only — edit via MCP/LLM and regenerate the report.'),
  );

const BASE = '/api';

async function request<T>(path: string, options?: RequestInit): Promise<T> {
  const res = await fetch(`${BASE}${path}`, {
    headers: { 'Content-Type': 'application/json' },
    ...options,
  });
  if (!res.ok) {
    let detail = res.statusText;
    try {
      const body = await res.json();
      if (body.error) detail = body.error;
      else if (body.message) detail = body.message;
    } catch {
      // body not JSON, keep statusText
    }
    throw new Error(`API error: ${res.status} ${detail}`);
  }
  return res.json();
}

export const api = {
  getBacklog: () =>
    SNAP
      ? Promise.resolve({ items: SNAP.backlog })
      : request<{ items: WorkItem[] }>('/backlog'),

  updateItem: (type: string, id: string, data: Partial<WorkItem>) =>
    SNAP
      ? readonly()
      : request<WorkItem>(`/backlog/${type}/${id}`, {
          method: 'PUT',
          body: JSON.stringify(data),
        }),

  createItem: (type: string, data: Partial<WorkItem>) =>
    SNAP
      ? readonly()
      : request<WorkItem>(`/backlog/${type}`, {
          method: 'POST',
          body: JSON.stringify(data),
        }),

  getPeople: () =>
    SNAP
      ? Promise.resolve({ people: SNAP.people, teams: SNAP.teams, project: SNAP.project })
      : request<{ people: Person[]; teams: Team[]; project: ProjectConfig }>('/people'),

  getConfig: () =>
    SNAP
      ? Promise.resolve({ pis: SNAP.pis, project: SNAP.project })
      : request<{ pis: PIConfig[]; project: ProjectConfig }>('/config'),

  getGitStatus: () =>
    SNAP ? Promise.resolve(SNAP.git) : request<GitStatus>('/git/status'),

  commit: (message: string) =>
    SNAP
      ? readonly()
      : request<{ hash: string }>('/git/commit', {
          method: 'POST',
          body: JSON.stringify({ message }),
        }),

  createBranch: (name: string) =>
    SNAP
      ? readonly()
      : request<{ branch: string }>('/git/branch', {
          method: 'POST',
          body: JSON.stringify({ name }),
        }),

  getObjectives: (piId: string) =>
    SNAP
      ? Promise.resolve(SNAP.objectives?.[piId] ?? { pi: piId, teams: {} })
      : request<ObjectivesData>(`/objectives/${piId}`),

  saveObjectives: (piId: string, data: ObjectivesData) =>
    SNAP
      ? readonly()
      : request<ObjectivesData>(`/objectives/${piId}`, {
          method: 'PUT',
          body: JSON.stringify(data),
        }),
};
